#!/bin/sh

set -e
set -x


exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH


payload=$(mktemp -t $TMPDIR/openjdk-resource-in-request.XXXXXX)

# putting things you get from stdin to payload
cat > ${payload} <&0

arch=$(jq -r '.source.repository // ""' < ${payload})
platform=$(jq -r '.source.platform // ""' < ${payload})
version=$(jq -r '.version.version // ""' < ${payload})
fetch_tarball=$(jq -r '.params.tarball != false' < ${payload})

if [ -z "$arch" ]; then
  arch="x64"
fi

if [ -z "$platform" ]; then
  platform="linux"
fi

if [ -z "$version" ]; then
  echo "must specify version"
  exit 1
fi


mkdir -p ${destination}


download_url=$(curl --retry 5 -L -s -f https://jdk8.java.net/download.html |grep ${platform} |grep "binaries/jdk" | grep ${arch} |grep tar.gz|cut -d'=' -f2|cut -d'"' -f2)
echo "Cheking url: ${download_url}"

detected_version=$(echo ${download_url}| awk -F'[/]' '{print $NF}'| awk -F'.' '{print $1}')
echo "detected_version: ${detected_version}"

if [ "${detected_version}" != "${version}" ]
then
    echo " Detected version (${detected_version}) does not match 'in version' (${version})"
    exit 1
fi

echo "$download_url" > ${destination}/url
echo "$version" > ${destination}/version

if [ "$fetch_tarball" = "true" ]; then
  curl --retry 5 --fail -L "$download_url" -o ${destination}/release.tgz
  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" ${download_url}
fi

jq -n '{
  version: {
    version: $version
  },
  metadata: [
    {name: "url", value: $url}
  ]
}' --arg version "$version" --arg url "$download_url" >&3

set +x